services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=flood_shelters
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mysecret
      - MYSQL_ROOT_PASSWORD=rootpass
    restart: always

volumes:
  data:
